datasource:
  sampleapp:
    url: jdbc:postgresql://ec2-34-192-30-15.compute-1.amazonaws.com:5432/de4ihmmv96bur5?user=ibdtmmzqbjvhuh&password=5d7e669c7d040f8b9b56932863636ad8066a77fd4b77ce55338238a24898e9b3
    username: ibdtmmzqbjvhuh
    password: 5d7e669c7d040f8b9b56932863636ad8066a77fd4b77ce55338238a24898e9b3
    driverClassName: org.postgresql.Driver
    defaultSchema:
#    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
